repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
      - id: mypy
        args: [--check-untyped-defs]
        additional_dependencies: [pygame, pytest]
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3
